// Write src/version.ts from package.json, so the engine this package loads is
// its own X.Y and cannot drift from what npm publishes.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const pkg = JSON.parse(readFileSync(fileURLToPath(new URL('../package.json', import.meta.url)), 'utf8'));
if (!/^\d+\.\d+\.\d+/.test(pkg.version)) throw new Error(`package.json version is not semver: ${pkg.version}`);
const out = fileURLToPath(new URL('../src/version.ts', import.meta.url));
writeFileSync(
  out,
  `// Generated by scripts/stamp-version.mjs from package.json. Do not edit.\nexport const VERSION = ${JSON.stringify(pkg.version)};\n`,
);
